/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Q3;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maianhtran
 */
public class showAllCDs extends javax.swing.JFrame {

    private JTable table;
    private DefaultTableModel model;

    /**
     * Creates new form showAllCDs
     */
    public showAllCDs(ArrayList<CD> CDs) {
        initComponents();

        setTitle("CD List");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setPreferredSize(new Dimension(400, 300));
        setSize(455, 350);
        setLocationRelativeTo(null);

        model = new DefaultTableModel();
        table = new JTable(model);
        model.addColumn("CD ID");
        model.addColumn("CD Title");
        model.addColumn("CD Collection");
        model.addColumn("CD Type");
        model.addColumn("CD Price");
        model.addColumn("CD Year of Release");

        JScrollPane scrollPane = new JScrollPane(table);
        getContentPane().add(scrollPane, BorderLayout.CENTER);

        for (CD cd : CDs) {
            Object[] rows = new Object[]{
                cd.getCDId(), cd.getTitle(), cd.getCDcollection(), cd.getCDtype(), cd.getPrice(), cd.getYearOfRelease()
            };
            model.addRow(rows);
        }
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
