/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ck5;

import javax.swing.JOptionPane;

/**
 *
 * @author maianhtran
 */
public class MotorcycleFrame extends javax.swing.JFrame {

    /**
     * Creates new form MotorcycleFrame
     */
    public MotorcycleFrame() {
        initComponents();

        setLocationRelativeTo(null);

        printArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customerNameLabel = new javax.swing.JLabel();
        ticketIDLabel = new javax.swing.JLabel();
        customerIDLabel = new javax.swing.JLabel();
        licensePlatesLabel = new javax.swing.JLabel();
        noOfDayLabel = new javax.swing.JLabel();
        extraPackageLabel = new javax.swing.JLabel();
        motorcycleTypeLabel = new javax.swing.JLabel();
        voucherLabel = new javax.swing.JLabel();
        ticketIDField = new javax.swing.JTextField();
        customerNameField = new javax.swing.JTextField();
        customerIDField = new javax.swing.JTextField();
        licensePlatesField = new javax.swing.JTextField();
        noOfDayField = new javax.swing.JTextField();
        voucherField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        suiteCheckBox = new javax.swing.JCheckBox();
        helmetCheckBox = new javax.swing.JCheckBox();
        typeComboBox = new javax.swing.JComboBox<>();
        cargoBoxCheckBox = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        printArea = new javax.swing.JTextArea();
        ticketInformationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Captain Motorcycle Rental Services");

        customerNameLabel.setText("Customer Name");

        ticketIDLabel.setText("Ticket ID");

        customerIDLabel.setText("Customer ID");

        licensePlatesLabel.setText("License Plates");

        noOfDayLabel.setText("No Of Day");

        extraPackageLabel.setText("Extra Package");

        motorcycleTypeLabel.setText("Motorcycle Type");

        voucherLabel.setText("Voucher");

        ticketIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ticketIDFieldActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        printButton.setText("Print Ticket");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        suiteCheckBox.setText("Suite");

        helmetCheckBox.setText("Helmet");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Scooter", "Naked Bike", "Adventure Bike", "Cruiser" }));

        cargoBoxCheckBox.setText("Cargo box");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(voucherLabel)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(customerIDLabel)
                                    .addComponent(customerNameLabel)
                                    .addComponent(ticketIDLabel)
                                    .addComponent(licensePlatesLabel)
                                    .addComponent(noOfDayLabel)
                                    .addComponent(motorcycleTypeLabel)
                                    .addComponent(extraPackageLabel))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ticketIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                                            .addComponent(customerNameField)
                                            .addComponent(customerIDField)
                                            .addComponent(licensePlatesField)
                                            .addComponent(noOfDayField)
                                            .addComponent(typeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(voucherField, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(helmetCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(suiteCheckBox)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(cargoBoxCheckBox)))
                                        .addGap(31, 31, 31))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(printButton)
                        .addGap(42, 42, 42)
                        .addComponent(clearButton)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketIDLabel))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameLabel)
                    .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDLabel)
                    .addComponent(customerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(licensePlatesLabel)
                    .addComponent(licensePlatesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noOfDayLabel)
                    .addComponent(noOfDayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(motorcycleTypeLabel)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extraPackageLabel)
                    .addComponent(helmetCheckBox)
                    .addComponent(suiteCheckBox)
                    .addComponent(cargoBoxCheckBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voucherLabel)
                    .addComponent(voucherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printButton)
                    .addComponent(clearButton))
                .addGap(61, 61, 61))
        );

        printArea.setColumns(20);
        printArea.setRows(5);
        jScrollPane1.setViewportView(printArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        ticketInformationLabel.setText("Ticket Information");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(ticketInformationLabel)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ticketInformationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ticketIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ticketIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ticketIDFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        ticketIDField.setText("");
        customerNameField.setText("");
        customerIDField.setText("");
        licensePlatesField.setText("");
        noOfDayField.setText("");
        typeComboBox.setSelectedIndex(0);
        helmetCheckBox.setSelected(false);
        suiteCheckBox.setSelected(false);
        cargoBoxCheckBox.setSelected(false);
        voucherField.setText("");
        printArea.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            if (ticketIDField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ticket ID cannot be blanked.");
                ticketIDField.requestFocus();
                return;
            }
            if (customerNameField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Customer Name cannot be blanked.");
                customerNameField.requestFocus();
                return;
            }
            if (customerIDField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Customer ID cannot be blanked.");
                customerIDField.requestFocus();
                return;
            }
            if (licensePlatesField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "License Plates cannot be blanked.");
                licensePlatesField.requestFocus();
                return;
            }
            if (noOfDayField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No Of Day cannot be blanked.");
                noOfDayField.requestFocus();
                return;
            }
            if (voucherField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Voucher cannot be blanked.");
                voucherField.requestFocus();
                return;
            }

            int ticketID = Integer.parseInt(ticketIDField.getText());
            String customerName = customerNameField.getText();
            String customerID = customerIDField.getText();
            String licensePlatesNumbers = licensePlatesField.getText();
            String motorcycleType = (String) typeComboBox.getSelectedItem();
            int noOfDay = Integer.parseInt(noOfDayField.getText());
            String extraPackage = "";
            if (helmetCheckBox.isSelected()) {
                extraPackage += "Helmet, ";
            }
            if (suiteCheckBox.isSelected()) {
                extraPackage += "Suite, ";
            }
            if (cargoBoxCheckBox.isSelected()) {
                extraPackage += "Cargo Box, ";
            }

            extraPackage = extraPackage.substring(0, extraPackage.length() - 2);

            float voucher = Float.parseFloat(voucherField.getText());

            MotorcycleRentalTicket m = new MotorcycleRentalTicket(ticketID, customerName, customerID, licensePlatesNumbers, motorcycleType, noOfDay, extraPackage, voucher);

            float payment = m.getPaymnet();

            printArea.setText("Ticket ID:\t" + ticketID + "\n"
                    + "Customer Name:\t" + customerName + "\n"
                    + "Customer ID:\t" + customerID + "\n"
                    + "License Plates:\t" + licensePlatesNumbers + "\n"
                    + "No Of Day:\t" + noOfDay + "\n"
                    + "Motor Type:\t" + motorcycleType + "\n"
                    + "Extra Package:\t" + extraPackage + "\n"
                    + "----*----Payment:\t" + payment + "\n");

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ticket ID, No Of Day and Voucher should be numbers.");
            return;
        }
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cargoBoxCheckBox;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField customerIDField;
    private javax.swing.JLabel customerIDLabel;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JLabel extraPackageLabel;
    private javax.swing.JCheckBox helmetCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField licensePlatesField;
    private javax.swing.JLabel licensePlatesLabel;
    private javax.swing.JLabel motorcycleTypeLabel;
    private javax.swing.JTextField noOfDayField;
    private javax.swing.JLabel noOfDayLabel;
    private javax.swing.JTextArea printArea;
    private javax.swing.JButton printButton;
    private javax.swing.JCheckBox suiteCheckBox;
    private javax.swing.JTextField ticketIDField;
    private javax.swing.JLabel ticketIDLabel;
    private javax.swing.JLabel ticketInformationLabel;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JTextField voucherField;
    private javax.swing.JLabel voucherLabel;
    // End of variables declaration//GEN-END:variables
}
