/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ck3;

import javax.swing.JOptionPane;

/**
 *
 * @author maianhtran
 */
public class WakandaPetServicesFrame extends javax.swing.JFrame {

    /**
     * Creates new form WakandaPetServicesFrame
     */
    public WakandaPetServicesFrame() {
        initComponents();

        setLocationRelativeTo(null);

        generalCheckCheckBox.setSelected(true);
        generalCheckCheckBox.setEnabled(false);
        dogRadioButton.setSelected(true);
        printArea.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        typeButtonGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        customerNameLabel = new javax.swing.JLabel();
        ticketIDField = new javax.swing.JTextField();
        ticketIDLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        petTypeLabel = new javax.swing.JLabel();
        basePriceLabel = new javax.swing.JLabel();
        petSizeLabel = new javax.swing.JLabel();
        voucherLabel = new javax.swing.JLabel();
        servicesLabel = new javax.swing.JLabel();
        basePriceField = new javax.swing.JTextField();
        customerNameField = new javax.swing.JTextField();
        phoneField = new javax.swing.JTextField();
        dogRadioButton = new javax.swing.JRadioButton();
        catRadioButton = new javax.swing.JRadioButton();
        voucherField = new javax.swing.JTextField();
        sizeComboBox = new javax.swing.JComboBox<>();
        generalCheckCheckBox = new javax.swing.JCheckBox();
        brushingCheckBox = new javax.swing.JCheckBox();
        washingCheckBox = new javax.swing.JCheckBox();
        clippingCheckBox = new javax.swing.JCheckBox();
        groomingCheckBox = new javax.swing.JCheckBox();
        printButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        printArea = new javax.swing.JTextArea();
        ticketInformationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        customerNameLabel.setText("Customer Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 32, 0, 0);
        jPanel1.add(customerNameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 59;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(41, 33, 0, 35);
        jPanel1.add(ticketIDField, gridBagConstraints);

        ticketIDLabel.setText("Ticket ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(44, 32, 0, 0);
        jPanel1.add(ticketIDLabel, gridBagConstraints);

        phoneLabel.setText("Phone");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 32, 0, 0);
        jPanel1.add(phoneLabel, gridBagConstraints);

        petTypeLabel.setText("Pet type");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(26, 32, 0, 0);
        jPanel1.add(petTypeLabel, gridBagConstraints);

        basePriceLabel.setText("Base Price");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 32, 0, 0);
        jPanel1.add(basePriceLabel, gridBagConstraints);

        petSizeLabel.setText("Pet size");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 32, 0, 0);
        jPanel1.add(petSizeLabel, gridBagConstraints);

        voucherLabel.setText("Voucher");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(32, 32, 0, 0);
        jPanel1.add(voucherLabel, gridBagConstraints);

        servicesLabel.setText("Services:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 32, 0, 0);
        jPanel1.add(servicesLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 59;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 33, 0, 35);
        jPanel1.add(basePriceField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 59;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 33, 0, 35);
        jPanel1.add(customerNameField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 59;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(23, 33, 0, 35);
        jPanel1.add(phoneField, gridBagConstraints);

        typeButtonGroup.add(dogRadioButton);
        dogRadioButton.setText("Dog");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 2, 0, 0);
        jPanel1.add(dogRadioButton, gridBagConstraints);

        typeButtonGroup.add(catRadioButton);
        catRadioButton.setText("Cat");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 33;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 36;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 13, 0, 0);
        jPanel1.add(catRadioButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 59;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 139;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 33, 0, 35);
        jPanel1.add(voucherField, gridBagConstraints);

        sizeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large", "Extra Large" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 59;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 102;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(24, 33, 0, 35);
        jPanel1.add(sizeComboBox, gridBagConstraints);

        generalCheckCheckBox.setText("General Check");
        generalCheckCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generalCheckCheckBoxActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 15, 0, 0);
        jPanel1.add(generalCheckCheckBox, gridBagConstraints);

        brushingCheckBox.setText("Brushing");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 37, 0, 0);
        jPanel1.add(brushingCheckBox, gridBagConstraints);

        washingCheckBox.setText("Washing");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(28, 42, 0, 0);
        jPanel1.add(washingCheckBox, gridBagConstraints);

        clippingCheckBox.setText("Clipping");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(27, 42, 0, 0);
        jPanel1.add(clippingCheckBox, gridBagConstraints);

        groomingCheckBox.setText("Grooming");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 24;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(29, 37, 0, 0);
        jPanel1.add(groomingCheckBox, gridBagConstraints);

        printButton.setText("Print Ticket");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 2, 22, 0);
        jPanel1.add(printButton, gridBagConstraints);

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 22;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridwidth = 35;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(33, 6, 22, 0);
        jPanel1.add(clearButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 15, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        printArea.setColumns(20);
        printArea.setRows(5);
        jScrollPane1.setViewportView(printArea);

        ticketInformationLabel.setText("Ticket Information");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ticketInformationLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ticketInformationLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 29;
        gridBagConstraints.ipady = 32;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 28, 15, 32);
        getContentPane().add(jPanel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generalCheckCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generalCheckCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_generalCheckCheckBoxActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        ticketIDField.setText("");
        customerNameField.setText("");
        phoneField.setText("");
        basePriceField.setText("");
        typeButtonGroup.clearSelection();
        sizeComboBox.setSelectedIndex(0);
        voucherField.setText("");
        washingCheckBox.setSelected(false);
        groomingCheckBox.setSelected(false);
        clippingCheckBox.setSelected(false);
        brushingCheckBox.setSelected(false);
        printArea.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        try {
            if (ticketIDField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ticket ID cannot be blanked.");
                ticketIDField.requestFocus();
                return;
            }
            if (customerNameField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Customer Name cannot be blanked.");
                customerNameField.requestFocus();
                return;
            }
            if (phoneField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Phone cannot be blanked.");
                phoneField.requestFocus();
                return;
            }
            if (basePriceField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Base Price cannot be blanked.");
                basePriceField.requestFocus();
                return;
            }
            if (voucherField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Voucher cannot be blanked.");
                voucherField.requestFocus();
                return;
            }

            int ticketID = Integer.parseInt(ticketIDField.getText());
            String customerName = customerNameField.getText();
            String phone = phoneField.getText();
            float basePrice = Float.parseFloat(basePriceField.getText());
            String type = "";
            if (dogRadioButton.isSelected()) {
                type += "Dog";
            }
            if (catRadioButton.isSelected()) {
                type += "Cat";
            }
            String size = (String) sizeComboBox.getSelectedItem();
            float voucher = Float.parseFloat(voucherField.getText());
            String services = "";
            if (generalCheckCheckBox.isSelected()) {
                services += "General Check, ";
            }
            if (washingCheckBox.isSelected()) {
                services += "Washing, ";
            }
            if (groomingCheckBox.isSelected()) {
                services += "Grooming, ";
            }
            if (clippingCheckBox.isSelected()) {
                services += "Clipping, ";
            }
            if (brushingCheckBox.isSelected()) {
                services += "Brushing, ";
            }

            services = services.substring(0, services.length() - 2);

            PetServicesTicketFee p = new PetServicesTicketFee(ticketID, customerName, phone, type, size, basePrice, services, voucher);

            float payment = p.getPayment();

            printArea.setText("Ticket ID:\t" + ticketID + "\n"
                    + "Customer:\t" + customerName + "\n"
                    + "Phone:\t" + phone + "\n"
                    + "Type:\t" + type + "\n"
                    + "Size:\t" + size + "\n"
                    + "Services:\t" + services + "\n"
                    + "----*----Payment:\t" + payment + "\n");
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ticket ID, Base Price and Voucher should be numbers.");
            return;
        }
    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField basePriceField;
    private javax.swing.JLabel basePriceLabel;
    private javax.swing.JCheckBox brushingCheckBox;
    private javax.swing.JRadioButton catRadioButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JCheckBox clippingCheckBox;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JRadioButton dogRadioButton;
    private javax.swing.JCheckBox generalCheckCheckBox;
    private javax.swing.JCheckBox groomingCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel petSizeLabel;
    private javax.swing.JLabel petTypeLabel;
    private javax.swing.JTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JTextArea printArea;
    private javax.swing.JButton printButton;
    private javax.swing.JLabel servicesLabel;
    private javax.swing.JComboBox<String> sizeComboBox;
    private javax.swing.JTextField ticketIDField;
    private javax.swing.JLabel ticketIDLabel;
    private javax.swing.JLabel ticketInformationLabel;
    private javax.swing.ButtonGroup typeButtonGroup;
    private javax.swing.JTextField voucherField;
    private javax.swing.JLabel voucherLabel;
    private javax.swing.JCheckBox washingCheckBox;
    // End of variables declaration//GEN-END:variables
}
