/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ck4;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maianhtran
 */
public class BlackPantherResortServices extends javax.swing.JFrame {

    /**
     * Creates new form BlackPantherResortServices
     */
    private ArrayList<BungalowRentalTicket> listTicket = new ArrayList<>();

    public BlackPantherResortServices() {
        initComponents();
        setLocationRelativeTo(null);
        printArea.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customerNameLabel = new javax.swing.JLabel();
        ticketIDLabel = new javax.swing.JLabel();
        customerIDLabel = new javax.swing.JLabel();
        customerPhoneLabel = new javax.swing.JLabel();
        noOfDayLabel = new javax.swing.JLabel();
        extraPackageLabel = new javax.swing.JLabel();
        bungalowTypeLabel = new javax.swing.JLabel();
        voucherLabel = new javax.swing.JLabel();
        ticketIDField = new javax.swing.JTextField();
        voucherField = new javax.swing.JTextField();
        noOfDayField = new javax.swing.JTextField();
        customerNameField = new javax.swing.JTextField();
        customerPhoneField = new javax.swing.JTextField();
        customerIDField = new javax.swing.JTextField();
        bungalowTypeComboBox = new javax.swing.JComboBox<>();
        buffetCheckBox = new javax.swing.JCheckBox();
        spaCheckBox = new javax.swing.JCheckBox();
        gymCheckBox = new javax.swing.JCheckBox();
        printButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        editButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        ticketInformationLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        printArea = new javax.swing.JTextArea();
        searchField = new javax.swing.JTextField();
        searchButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ticketTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Black Panther Resort Services");

        customerNameLabel.setText("Customer Name");

        ticketIDLabel.setText("Ticket ID");

        customerIDLabel.setText("Customer ID");

        customerPhoneLabel.setText("Customer Phone");

        noOfDayLabel.setText("No Of Day");

        extraPackageLabel.setText("Extra Package");

        bungalowTypeLabel.setText("Bungalow Type");

        voucherLabel.setText("Voucher");

        bungalowTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Single", "Double", "Deluxe", "Presidential" }));

        buffetCheckBox.setText("Buffet");

        spaCheckBox.setText("Spa");

        gymCheckBox.setText("Gym");

        printButton.setText("Print Ticket");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(deleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(printButton)
                                .addGap(46, 46, 46)
                                .addComponent(clearButton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(voucherLabel)
                                    .addGap(63, 63, 63)
                                    .addComponent(voucherField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(extraPackageLabel)
                                    .addGap(223, 223, 223)))
                            .addComponent(customerIDLabel, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(customerPhoneLabel, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap(19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ticketIDLabel)
                            .addComponent(customerNameLabel)
                            .addComponent(noOfDayLabel)
                            .addComponent(bungalowTypeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ticketIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(customerPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(noOfDayField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bungalowTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buffetCheckBox)
                                .addGap(33, 33, 33)
                                .addComponent(spaCheckBox)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(gymCheckBox)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketIDLabel)
                    .addComponent(ticketIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameLabel))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerIDLabel)
                    .addComponent(customerIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerPhoneLabel)
                    .addComponent(customerPhoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noOfDayField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noOfDayLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bungalowTypeLabel)
                    .addComponent(bungalowTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extraPackageLabel)
                    .addComponent(buffetCheckBox)
                    .addComponent(gymCheckBox)
                    .addComponent(spaCheckBox))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voucherLabel)
                    .addComponent(voucherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printButton)
                    .addComponent(clearButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton)
                    .addComponent(editButton))
                .addContainerGap(59, Short.MAX_VALUE))
        );

        ticketInformationLabel.setText("Ticket Information");

        printArea.setColumns(20);
        printArea.setRows(5);
        jScrollPane1.setViewportView(printArea);

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        ticketTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ticket ID", "Customer Name", "Customer ID", "Customer Phone", "No Of Day", "Bungalow Type", "Extra Package", "Voucher"
            }
        ));
        ticketTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ticketTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ticketTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ticketInformationLabel)
                        .addGap(292, 292, 292)
                        .addComponent(searchButton)
                        .addGap(79, 79, 79)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketInformationLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed

        ticketIDField.setText("");
        customerNameField.setText("");
        customerIDField.setText("");
        customerPhoneField.setText("");
        noOfDayField.setText("");
        bungalowTypeComboBox.setSelectedIndex(0);
        buffetCheckBox.setSelected(false);
        spaCheckBox.setSelected(false);
        gymCheckBox.setSelected(false);
        voucherField.setText("");
        printArea.setText("");

    }//GEN-LAST:event_clearButtonActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed

        try {
            if (ticketIDField.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Ticket ID cannot be blanked.");
                ticketIDField.requestFocus();
                return;
            }
            if (customerNameField.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Customer Name cannot be blanked.");
                customerNameField.requestFocus();
                return;
            }
            if (customerIDField.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Customer ID cannot be blanked.");
                customerIDField.requestFocus();
                return;
            }
            if (customerPhoneField.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Customer Phone cannot be blanked.");
                customerPhoneField.requestFocus();
                return;
            }
            if (noOfDayField.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "No Of Day cannot blanked.");
                noOfDayField.requestFocus();
                return;
            }
            if (voucherField.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Voucher cannot be blanked.");
                voucherField.requestFocus();
                return;
            }

            int ticketID = Integer.parseInt(ticketIDField.getText());
            String customerName = customerNameField.getText();
            String customerID = customerIDField.getText();
            String customerPhone = customerPhoneField.getText();
            int noOfDay = Integer.parseInt(noOfDayField.getText());
            String bungalowType = (String) bungalowTypeComboBox.getSelectedItem();
            String extraPackage = "";
            if (buffetCheckBox.isSelected()) {
                extraPackage += "Buffet, ";
            }
            if (spaCheckBox.isSelected()) {
                extraPackage += "Spa, ";
            }
            if (gymCheckBox.isSelected()) {
                extraPackage += "Gym, ";
            }
            extraPackage = extraPackage.isEmpty() ? "None" : extraPackage.substring(0, extraPackage.length() - 2);
            float voucher = Float.parseFloat(voucherField.getText());

            BungalowRentalTicket ticket = new BungalowRentalTicket(ticketID, customerName, customerID, customerPhone, bungalowType, noOfDay, extraPackage, voucher);
            float payment = ticket.getPayment();

            listTicket.add(ticket);

            printArea.setText(ticket.toString());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ticket ID, No Of Day and Voucher should be numbers.");
            return;
        }
        fillInTicketTable();
    }//GEN-LAST:event_printButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed

        if (listTicket.isEmpty()) {
            JOptionPane.showMessageDialog(this, "There are no tickets to delete.");
            return;
        }

        String input = JOptionPane.showInputDialog(this, "Enter Ticket ID to delete");
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed

        updateDateFromTable();
        fillInTicketTable();
    }//GEN-LAST:event_editButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void ticketTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ticketTableMouseClicked
        updateDateFromTable();

    }//GEN-LAST:event_ticketTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public void updateDateFromTable() {
        DefaultTableModel model = (DefaultTableModel) ticketTable.getModel();

        int selectedRow = ticketTable.getSelectedRow();
        BungalowRentalTicket ticket = listTicket.get(selectedRow);
        customerNameField.setText(ticket.getCustomerName().toString());
        customerIDField.setText(ticket.getCustomerID().toString());
        customerPhoneField.setText(ticket.getCustomerPhone().toString());
        noOfDayField.setText(String.valueOf(ticket.getNoOfDay()));
        bungalowTypeComboBox.setSelectedItem(ticket.getBungalowType());

        listTicket.set(selectedRow, ticket);
    }

    public void fillInTicketTable() {
        DefaultTableModel model = (DefaultTableModel) ticketTable.getModel();

        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }

        for (BungalowRentalTicket ticket : listTicket) {
            Object[] rows = new Object[]{ticket.getTicketID(), ticket.getCustomerName(), ticket.getCustomerID(), ticket.getCustomerPhone(), ticket.getNoOfDay(), ticket.getBungalowType(), ticket.getExtraPackage()};
            model.addRow(rows);
        }

        pack();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox buffetCheckBox;
    private javax.swing.JComboBox<String> bungalowTypeComboBox;
    private javax.swing.JLabel bungalowTypeLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField customerIDField;
    private javax.swing.JLabel customerIDLabel;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JTextField customerPhoneField;
    private javax.swing.JLabel customerPhoneLabel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel extraPackageLabel;
    private javax.swing.JCheckBox gymCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField noOfDayField;
    private javax.swing.JLabel noOfDayLabel;
    private javax.swing.JTextArea printArea;
    private javax.swing.JButton printButton;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JCheckBox spaCheckBox;
    private javax.swing.JTextField ticketIDField;
    private javax.swing.JLabel ticketIDLabel;
    private javax.swing.JLabel ticketInformationLabel;
    private javax.swing.JTable ticketTable;
    private javax.swing.JTextField voucherField;
    private javax.swing.JLabel voucherLabel;
    // End of variables declaration//GEN-END:variables
}
