/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ck;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author maianhtran
 */
public class ShoesServicesFrame extends javax.swing.JFrame {

    /**
     * Creates new form ShoesServicesFrame
     */
    private ArrayList<ShoesServicesTicket> ticketList = new ArrayList<>();

    public ShoesServicesFrame() {
        initComponents();

        setLocationRelativeTo(null);

        washingCheckBox.setSelected(true);
        washingCheckBox.setEnabled(false);
        ticketTextArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel1 = new javax.swing.JPanel();
        ticketIDLabel = new javax.swing.JLabel();
        customerNameLabel = new javax.swing.JLabel();
        brandLabel = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        colorLabel = new javax.swing.JLabel();
        laborPriceLabel = new javax.swing.JLabel();
        servicesLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();
        voucherLabel = new javax.swing.JLabel();
        ticketIDField = new javax.swing.JTextField();
        customerNameField = new javax.swing.JTextField();
        brandField = new javax.swing.JTextField();
        modelField = new javax.swing.JTextField();
        colorField = new javax.swing.JTextField();
        voucherField = new javax.swing.JTextField();
        washingCheckBox = new javax.swing.JCheckBox();
        renewSoleCheckBox = new javax.swing.JCheckBox();
        customPaintCheckBox = new javax.swing.JCheckBox();
        repairCheckBox = new javax.swing.JCheckBox();
        renewUpperCheckBox = new javax.swing.JCheckBox();
        laborPriceField = new javax.swing.JTextField();
        clearButton = new javax.swing.JButton();
        printButton = new javax.swing.JButton();
        typeComboBox = new javax.swing.JComboBox<>();
        JPanel2 = new javax.swing.JPanel();
        ticketInformationLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ticketTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atlantis Shoes Services");

        ticketIDLabel.setText("Ticket ID");

        customerNameLabel.setText("Customer Name");

        brandLabel.setText("Brand");

        modelLabel.setText("Model");

        colorLabel.setText("Color");

        laborPriceLabel.setText("Labor Price");

        servicesLabel.setText("Services:");

        typeLabel.setText("Type");

        voucherLabel.setText("Voucher");

        colorField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorFieldActionPerformed(evt);
            }
        });

        washingCheckBox.setText("Washing");
        washingCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                washingCheckBoxActionPerformed(evt);
            }
        });

        renewSoleCheckBox.setText("Renew Sole");

        customPaintCheckBox.setText("Custom Paint");
        customPaintCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customPaintCheckBoxActionPerformed(evt);
            }
        });

        repairCheckBox.setText("Repair");

        renewUpperCheckBox.setText("Renew Upper");

        laborPriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laborPriceFieldActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        printButton.setText("Print Ticket");
        printButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printButtonActionPerformed(evt);
            }
        });

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sandals", "Sneakers", "Leather Shoes" }));

        javax.swing.GroupLayout JPanel1Layout = new javax.swing.GroupLayout(JPanel1);
        JPanel1.setLayout(JPanel1Layout);
        JPanel1Layout.setHorizontalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addComponent(voucherLabel)
                        .addGap(18, 18, 18)
                        .addComponent(voucherField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(brandLabel)
                            .addComponent(renewUpperCheckBox)
                            .addComponent(repairCheckBox))
                        .addGap(35, 35, 35)
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(renewSoleCheckBox)
                            .addComponent(customPaintCheckBox)))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanel1Layout.createSequentialGroup()
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ticketIDLabel)
                                    .addComponent(customerNameLabel)
                                    .addComponent(typeLabel)
                                    .addComponent(colorLabel))
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel1Layout.createSequentialGroup()
                                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modelLabel)
                                    .addComponent(laborPriceLabel)
                                    .addComponent(servicesLabel))
                                .addGap(37, 37, 37)))
                        .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modelField, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(washingCheckBox)
                            .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(ticketIDField, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                .addComponent(customerNameField)
                                .addComponent(brandField)
                                .addComponent(colorField)
                                .addGroup(JPanel1Layout.createSequentialGroup()
                                    .addGap(47, 47, 47)
                                    .addComponent(laborPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 33, Short.MAX_VALUE))
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(printButton)
                .addGap(60, 60, 60)
                .addComponent(clearButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanel1Layout.setVerticalGroup(
            JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ticketIDLabel)
                    .addComponent(ticketIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerNameLabel))
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brandLabel)
                    .addComponent(brandField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLabel)
                    .addComponent(modelField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(colorLabel)
                    .addComponent(colorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(laborPriceLabel)
                    .addComponent(laborPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(typeLabel)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(servicesLabel)
                .addGap(9, 9, 9)
                .addComponent(washingCheckBox)
                .addGap(11, 11, 11)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(renewSoleCheckBox)
                    .addComponent(renewUpperCheckBox))
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(customPaintCheckBox))
                    .addGroup(JPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(repairCheckBox)))
                .addGap(18, 18, 18)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voucherField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(voucherLabel))
                .addGap(30, 30, 30)
                .addGroup(JPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(printButton)
                    .addComponent(clearButton))
                .addGap(42, 42, 42))
        );

        ticketInformationLabel.setText("Ticket Information");

        ticketTextArea.setColumns(20);
        ticketTextArea.setRows(5);
        jScrollPane1.setViewportView(ticketTextArea);

        javax.swing.GroupLayout JPanel2Layout = new javax.swing.GroupLayout(JPanel2);
        JPanel2.setLayout(JPanel2Layout);
        JPanel2Layout.setHorizontalGroup(
            JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ticketInformationLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        JPanel2Layout.setVerticalGroup(
            JPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ticketInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void customPaintCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customPaintCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customPaintCheckBoxActionPerformed

    private void colorFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorFieldActionPerformed

    private void laborPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laborPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laborPriceFieldActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        ticketIDField.setText("");
        customerNameField.setText("");
        brandField.setText("");
        modelField.setText("");
        colorField.setText("");
        laborPriceField.setText("");
        typeComboBox.setSelectedIndex(0);
        renewUpperCheckBox.setSelected(false);
        renewSoleCheckBox.setSelected(false);
        repairCheckBox.setSelected(false);
        customPaintCheckBox.setSelected(false);
        voucherField.setText("");
        ticketTextArea.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void washingCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_washingCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_washingCheckBoxActionPerformed

    private void printButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printButtonActionPerformed
        printTicketListToTextArea();
        try {
            if (ticketIDField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Ticket ID cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
                ticketIDField.requestFocus();
                return;
            }
            if (customerNameField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Customer Name cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
                customerNameField.requestFocus();
                return;
            }
            if (brandField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Brand cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
                brandField.requestFocus();
                return;
            }
            if (modelField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Model cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
                modelField.requestFocus();
                return;
            }
            if (colorField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Color can not be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
                colorField.requestFocus();
                return;
            }
            if (laborPriceField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Labor Price cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
                laborPriceField.requestFocus();
                return;
            }
            if (voucherField.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Voucher cannot be empty.", "Input Error", JOptionPane.ERROR_MESSAGE);
                voucherField.requestFocus();
                return;
            }

            int ticketID = Integer.parseInt(ticketIDField.getText());
            String customerName = customerNameField.getText();
            String brand = brandField.getText();
            String model = modelField.getText();
            String color = colorField.getText();
            String type = (String) typeComboBox.getSelectedItem();
            float laborPrice = Float.parseFloat(laborPriceField.getText());
            String services = "";

            if (washingCheckBox.isSelected()) {
                services += "Washing, ";
            }
            if (renewUpperCheckBox.isSelected()) {
                services += "Renew Upper, ";
            }
            if (renewSoleCheckBox.isSelected()) {
                services += "Renew Sole, ";
            }
            if (repairCheckBox.isSelected()) {
                services += "Repair, ";
            }
            if (customPaintCheckBox.isSelected()) {
                services += "Custom Paint, ";
            }

            services = services.substring(0, services.length() - 2);

            float voucher = Float.parseFloat(voucherField.getText());

            if (ticketID <= 0 || laborPrice <= 0 || voucher < 0) {
                JOptionPane.showMessageDialog(this, "Ticket ID, Labor Price and Voucher shoule be positive numbers.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ShoesServicesTicket ticket = new ShoesServicesTicket(ticketID, customerName, brand, model, color, type, laborPrice, services, voucher);

            ticketList.add(ticket);

            float payment = ticket.getPayment();

            ticketTextArea.setText("Ticket ID:\t " + ticket.getTicketID() + "\n"
                    + "Customer:\t " + ticket.getCustomerName() + "\n"
                    + "Brand:\t " + ticket.getBrand() + "\n"
                    + "Model:\t " + ticket.getModel() + "\n"
                    + "Type:\t " + ticket.getType() + "\n"
                    + "Color:\t " + ticket.getColor() + "\n"
                    + "Services:\t " + ticket.getServices() + "\n"
                    + "----*----Payment:\t " + ticket.getPayment());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ticket ID, Labor Price and Voucher should be numbers.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_printButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    private void printTicketListToTextArea() {
        StringBuilder sb = new StringBuilder();
        for (ShoesServicesTicket ticket : ticketList) {
            sb.append("Ticket ID:\t ").append(ticket.getTicketID()).append("\n")
                    .append("Customer:\t ").append(ticket.getCustomerName()).append("\n")
                    .append("Brand:\t ").append(ticket.getBrand()).append("\n")
                    .append("Model:\t ").append(ticket.getModel()).append("\n")
                    .append("Type:\t ").append(ticket.getType()).append("\n")
                    .append("Color:\t ").append(ticket.getColor()).append("\n")
                    .append("Services:\t ").append(ticket.getServices()).append("\n")
                    .append("----*----Payment:\t ").append(ticket.getPayment()).append("\n\n");
        }
        ticketTextArea.setText(sb.toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel1;
    private javax.swing.JPanel JPanel2;
    private javax.swing.JTextField brandField;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JButton clearButton;
    private javax.swing.JTextField colorField;
    private javax.swing.JLabel colorLabel;
    private javax.swing.JCheckBox customPaintCheckBox;
    private javax.swing.JTextField customerNameField;
    private javax.swing.JLabel customerNameLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField laborPriceField;
    private javax.swing.JLabel laborPriceLabel;
    private javax.swing.JTextField modelField;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JButton printButton;
    private javax.swing.JCheckBox renewSoleCheckBox;
    private javax.swing.JCheckBox renewUpperCheckBox;
    private javax.swing.JCheckBox repairCheckBox;
    private javax.swing.JLabel servicesLabel;
    private javax.swing.JTextField ticketIDField;
    private javax.swing.JLabel ticketIDLabel;
    private javax.swing.JLabel ticketInformationLabel;
    private javax.swing.JTextArea ticketTextArea;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField voucherField;
    private javax.swing.JLabel voucherLabel;
    private javax.swing.JCheckBox washingCheckBox;
    // End of variables declaration//GEN-END:variables
}
