/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ck2;

import javax.swing.JOptionPane;

/**
 *
 * @author maianhtran
 */
public class PostageDashboard extends javax.swing.JFrame {

    /**
     * Creates new form PostageDashboard
     */
    public PostageDashboard() {
        initComponents();

        setLocationRelativeTo(null);

        printTextArea.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fromAddressLabel = new javax.swing.JLabel();
        toAddressLabel = new javax.swing.JLabel();
        basePriceLabel = new javax.swing.JLabel();
        packageTypeLabel = new javax.swing.JLabel();
        deliveryOptionLabel = new javax.swing.JLabel();
        valueOfInsuranceLabel = new javax.swing.JLabel();
        extraServicesLabel = new javax.swing.JLabel();
        fromAddressField = new javax.swing.JTextField();
        toAddressField = new javax.swing.JTextField();
        basePriceField = new javax.swing.JTextField();
        valueOfInsuranceField = new javax.swing.JTextField();
        currency1Label = new javax.swing.JLabel();
        signatureConfirmationCheckBox = new javax.swing.JCheckBox();
        insuranceCheckBox = new javax.swing.JCheckBox();
        typeComboBox = new javax.swing.JComboBox<>();
        deliveryOptionComboBox = new javax.swing.JComboBox<>();
        clearButton = new javax.swing.JButton();
        calculatePaymentButton = new javax.swing.JButton();
        currencyLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        printTextArea = new javax.swing.JTextArea();
        mailingSummaryLabel = new javax.swing.JLabel();
        packageInformationLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fromAddressLabel.setText("From Address");

        toAddressLabel.setText("To Address");

        basePriceLabel.setText("Base Price");

        packageTypeLabel.setText("Package Type");

        deliveryOptionLabel.setText("Delivery Option");

        valueOfInsuranceLabel.setText("Value of Insurance");

        extraServicesLabel.setText("Extra Services");

        fromAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromAddressFieldActionPerformed(evt);
            }
        });

        toAddressField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toAddressFieldActionPerformed(evt);
            }
        });

        basePriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                basePriceFieldActionPerformed(evt);
            }
        });

        valueOfInsuranceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valueOfInsuranceFieldActionPerformed(evt);
            }
        });

        currency1Label.setText("$");

        signatureConfirmationCheckBox.setText("Signature Confirmation");

        insuranceCheckBox.setText("Insurance");

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Envelope", "Small Box", "Medium Box", "Large Box" }));
        typeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeComboBoxActionPerformed(evt);
            }
        });

        deliveryOptionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Normal Delivery", "Express" }));

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        calculatePaymentButton.setText("Calculate Payment");
        calculatePaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculatePaymentButtonActionPerformed(evt);
            }
        });

        currencyLabel.setText("$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(calculatePaymentButton)
                .addGap(50, 50, 50)
                .addComponent(clearButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deliveryOptionLabel)
                    .addComponent(extraServicesLabel)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(basePriceLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(toAddressLabel)
                                .addComponent(fromAddressLabel))))
                    .addComponent(packageTypeLabel))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(valueOfInsuranceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(valueOfInsuranceField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(currency1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 49, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fromAddressField)
                            .addComponent(toAddressField)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(insuranceCheckBox)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(basePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(currencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(deliveryOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(typeComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(signatureConfirmationCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fromAddressLabel)
                    .addComponent(fromAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(toAddressLabel)
                    .addComponent(toAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(basePriceLabel)
                    .addComponent(basePriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currencyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(packageTypeLabel)
                    .addComponent(typeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deliveryOptionLabel)
                    .addComponent(deliveryOptionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(extraServicesLabel)
                    .addComponent(signatureConfirmationCheckBox))
                .addGap(28, 28, 28)
                .addComponent(insuranceCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(valueOfInsuranceLabel)
                    .addComponent(valueOfInsuranceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currency1Label))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculatePaymentButton)
                    .addComponent(clearButton))
                .addGap(48, 48, 48))
        );

        printTextArea.setColumns(20);
        printTextArea.setRows(5);
        jScrollPane1.setViewportView(printTextArea);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 461, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        mailingSummaryLabel.setText("Mailing Summary");

        packageInformationLabel.setText("Package Information");

        titleLabel.setText("Retail Postage Price Calculator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(packageInformationLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mailingSummaryLabel)
                        .addGap(365, 365, 365))))
            .addGroup(layout.createSequentialGroup()
                .addGap(413, 413, 413)
                .addComponent(titleLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(titleLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(packageInformationLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(mailingSummaryLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fromAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fromAddressFieldActionPerformed

    private void toAddressFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toAddressFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toAddressFieldActionPerformed

    private void basePriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_basePriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_basePriceFieldActionPerformed

    private void valueOfInsuranceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valueOfInsuranceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_valueOfInsuranceFieldActionPerformed

    private void calculatePaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculatePaymentButtonActionPerformed

        if (fromAddressField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "From address cannot be empty.");
            fromAddressField.requestFocus();
            return;
        }
        if (toAddressField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "To address cannot be empty.");
            toAddressField.requestFocus();
            return;
        }
        if (basePriceField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Base Price cannot be empty.");
            basePriceField.requestFocus();
            return;
        }

        if (insuranceCheckBox.isSelected() && valueOfInsuranceField.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Value Of Insurance cannot be blank.");
            valueOfInsuranceField.requestFocus();
            return;
        }
        try {
            if (insuranceCheckBox.isSelected() && valueOfInsuranceField.getText().isBlank()) {
                JOptionPane.showMessageDialog(this, "Value of Insurance cannot be blanked.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Base Price and Value of Insurance should be numbers");

        }

        String fromAddress = fromAddressField.getText();
        String toAddress = toAddressField.getText();
        float basePrice = Float.parseFloat(basePriceField.getText());
        String type = (String) typeComboBox.getSelectedItem();
        String deliveryOption = (String) deliveryOptionComboBox.getSelectedItem();

        String extraServices = "";

        if (signatureConfirmationCheckBox.isSelected()) {
            extraServices += "Signature Confirmation, ";
        }
        if (insuranceCheckBox.isSelected()) {
            extraServices += "Insurance, ";
        }

        float insuranceValue = Float.parseFloat(valueOfInsuranceField.getText());

        extraServices = extraServices.substring(0, extraServices.length() - 2);

        Package p = new Package(fromAddress, toAddress, basePrice, type, deliveryOption, extraServices, insuranceValue);

        float payment = p.calculatePayment();

        printTextArea.setText("From: " + fromAddress + "\n"
                + "To: " + toAddress + "\n"
                + "Package Type: " + type + "\n"
                + "Extra services: " + extraServices + "\n"
                + "Total payment: " + payment + "\n"
        );

        if (deliveryOptionComboBox.getSelectedItem().equals("Express")) {
            printTextArea.setText("Remarks: Mark the package \"Priority Mail\" in the postage area." + "\n");
        }


    }//GEN-LAST:event_calculatePaymentButtonActionPerformed

    private void typeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeComboBoxActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        fromAddressField.setText("");
        toAddressField.setText("");
        basePriceField.setText("");
        typeComboBox.setSelectedIndex(0);
        deliveryOptionComboBox.setSelectedIndex(0);
        signatureConfirmationCheckBox.setSelected(false);
        insuranceCheckBox.setSelected(false);
        valueOfInsuranceField.setText("");
        printTextArea.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField basePriceField;
    private javax.swing.JLabel basePriceLabel;
    private javax.swing.JButton calculatePaymentButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel currency1Label;
    private javax.swing.JLabel currencyLabel;
    private javax.swing.JComboBox<String> deliveryOptionComboBox;
    private javax.swing.JLabel deliveryOptionLabel;
    private javax.swing.JLabel extraServicesLabel;
    private javax.swing.JTextField fromAddressField;
    private javax.swing.JLabel fromAddressLabel;
    private javax.swing.JCheckBox insuranceCheckBox;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mailingSummaryLabel;
    private javax.swing.JLabel packageInformationLabel;
    private javax.swing.JLabel packageTypeLabel;
    private javax.swing.JTextArea printTextArea;
    private javax.swing.JCheckBox signatureConfirmationCheckBox;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField toAddressField;
    private javax.swing.JLabel toAddressLabel;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JTextField valueOfInsuranceField;
    private javax.swing.JLabel valueOfInsuranceLabel;
    // End of variables declaration//GEN-END:variables
}
