/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.lab7;

import java.io.*;
import java.util.ArrayList;
import javax.swing.*;

/**
 *
 * @author maianhtran
 */
public class NewCD extends javax.swing.JDialog {

    /**
     * Creates new form NewCD
     */
    private ArrayList<CD> CDs = new ArrayList<>();
    private DefaultListModel<String> listModel;
    private java.awt.event.ActionEvent evt;
    CDManager cdManager;
    // CD cd;

    public NewCD(java.awt.Frame parent, boolean modal, CDManager cdManager) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        this.cdManager = cdManager;

        setDefaultCloseOperation(HIDE_ON_CLOSE);

        //loadCDs();
    }

    //public CD getCD() {
    //  return cd;
    //}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type = new javax.swing.ButtonGroup();
        idLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        collectionLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        titleField = new javax.swing.JTextField();
        collectionComboBox = new javax.swing.JComboBox<>();
        typeLabel = new javax.swing.JLabel();
        VCDRadioButton = new javax.swing.JRadioButton();
        CDRadioButton = new javax.swing.JRadioButton();
        priceField = new javax.swing.JTextField();
        yearOfReleaseField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        idLabel.setText("CD ID");

        titleLabel.setText("CD Title");

        collectionLabel.setText("CD Collection");

        priceLabel.setText("CD Price");

        jLabel1.setText("CD Year of Release");

        collectionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "game", "movie", "music" }));

        typeLabel.setText("CD Type");

        type.add(VCDRadioButton);
        VCDRadioButton.setText("VCD");

        type.add(CDRadioButton);
        CDRadioButton.setText("CD");

        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(priceLabel)
                                .addGap(78, 78, 78)
                                .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(collectionLabel)
                                .addGap(18, 18, 18)
                                .addComponent(collectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(typeLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(titleLabel)
                                    .addComponent(idLabel))
                                .addGap(80, 80, 80)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(VCDRadioButton)
                                            .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(yearOfReleaseField, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addComponent(CDRadioButton))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(addButton)
                        .addGap(75, 75, 75)
                        .addComponent(clearButton)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idLabel)
                    .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(titleLabel)
                    .addComponent(titleField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(collectionLabel)
                    .addComponent(collectionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeLabel)
                    .addComponent(VCDRadioButton)
                    .addComponent(CDRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(yearOfReleaseField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clearButton)
                    .addComponent(addButton))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed

        String id = idField.getText();
        String title = titleField.getText();
        String collection = "";
        String type = "";
        String priceStr = priceField.getText();
        String yearStr = yearOfReleaseField.getText();

        if (VCDRadioButton.isSelected()) {
            type = "VCD";
        } else if (CDRadioButton.isSelected()) {
            type = "CD";
        }
        if (collectionComboBox.getSelectedIndex() != -1) {
            collection = (String) collectionComboBox.getItemAt(collectionComboBox.getSelectedIndex());
        }

        try {
            double price = Double.parseDouble(priceStr);
            int year = Integer.parseInt(yearStr);

            if (!id.isEmpty() && !title.isEmpty()) {

                CD cd2 = new CD(id, title, collection, type, price, year);
                //CDs.add(cd2);
                cdManager.getListCD().add(cd2);
                //saveInfor(); 
                JOptionPane.showMessageDialog(this, "Add successful.");
                saveCDs("CDs.DAT");
                this.setVisible(false);
                
                new CDStore(cdManager);
            } else {
                JOptionPane.showMessageDialog(this, "CD ID and CD Title can not be empty.");
                return;
            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "CD Price and CD Year of Release must be numbers.");

        }

    }//GEN-LAST:event_addButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        idField.setText("");
        titleField.setText("");
        collectionComboBox.setSelectedIndex(0);
        type.clearSelection();
        priceField.setText("");
        yearOfReleaseField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    /*public void saveCDs() {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("CDs.Dat"))) {

            oos.writeObject(cdManager.getListCD());
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving CDs to file.");
        }
    }*/

    public void loadCDs() {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("CDs.Dat"))) {
            cdManager.setListCD((ArrayList<CD>) ois.readObject());
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading CDs from file.");
        }
    }
    
    public void saveCDs(String fileName) {
        //CD(String id, String title, String collection, String type, double price, int year) 
        PrintWriter pw = null;
        try {
            pw = new PrintWriter(new FileWriter(fileName));
            for (CD cd : cdManager.getListCD()) {
                pw.println(cd.getId());
                pw.println(cd.getTitle());
                pw.println(cd.getCollection());
                pw.println(cd.getType());
                pw.println(String.format("%.2f", cd.getPrice()));
                pw.println(String.format("%d", cd.getYear()));

            }
            pw.flush();
        } catch (IOException ex) {
        } finally {
            pw.close();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton CDRadioButton;
    private javax.swing.JRadioButton VCDRadioButton;
    private javax.swing.JButton addButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> collectionComboBox;
    private javax.swing.JLabel collectionLabel;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel idLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField titleField;
    private javax.swing.JLabel titleLabel;
    private javax.swing.ButtonGroup type;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JTextField yearOfReleaseField;
    // End of variables declaration//GEN-END:variables
}
