/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Q1;

import java.awt.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.LineNumberReader;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maianhtran
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    StudentManager studentManager = new StudentManager();
    NewStudentDialog newStuDia = new NewStudentDialog();
    private DefaultTableModel tableModel;
    
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
        
        newStuDia.loadStudents(studentManager.listStudent);
        fillInStudentTable();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        checkTotalStudentButton = new javax.swing.JButton();
        newStudentButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Management");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkTotalStudentButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        checkTotalStudentButton.setText("Check total Student");
        checkTotalStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkTotalStudentButtonActionPerformed(evt);
            }
        });
        jPanel1.add(checkTotalStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 41, -1, -1));

        newStudentButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        newStudentButton.setText("New Student");
        newStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentButtonActionPerformed(evt);
            }
        });
        jPanel1.add(newStudentButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(315, 41, -1, -1));

        refreshButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });
        jPanel1.add(refreshButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 41, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 126, 0, 159);
        getContentPane().add(jPanel1, gridBagConstraints);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 567;
        gridBagConstraints.ipady = 407;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(8, 169, 0, 159);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentButtonActionPerformed
        new NewStudentDialog().setVisible(true);

    }//GEN-LAST:event_newStudentButtonActionPerformed

    private void checkTotalStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkTotalStudentButtonActionPerformed
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("Students.Dat"))) {
            studentManager.listStudent = (ArrayList<Student>) ois.readObject();
            JOptionPane.showMessageDialog(this, "There are " + studentManager.listStudent.size() + " students in the database");
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading students from file.");
        }

    }//GEN-LAST:event_checkTotalStudentButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        

    }//GEN-LAST:event_refreshButtonActionPerformed
    
    private void fillInStudentTable() {
        newStuDia.saveStudents(studentManager.getListStudent());
        tableModel.setRowCount(0);
        for (Student s : studentManager.listStudent) {
            Object[] rows = new Object[]{
                s.getStudentID(), s.getFirstName(), s.getLastName(), s.getGender(), s.getSchoolStage()
            };
            tableModel.addRow(rows);
        }
        jTable1.setModel(tableModel);
        pack();
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkTotalStudentButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton newStudentButton;
    private javax.swing.JButton refreshButton;
    // End of variables declaration//GEN-END:variables
}
