/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Q1;

import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;

/**
 *
 * @author maianhtran
 */
public class NewStudentDialog extends javax.swing.JFrame {

    /**
     * Creates new form NewStudentDialog
     */
    StudentManager studentManager = new StudentManager();

    public NewStudentDialog() {
        initComponents();
        setLocationRelativeTo(null);

        loadStudents(studentManager.listStudent );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        bg = new javax.swing.ButtonGroup();
        studentIDLabel = new javax.swing.JLabel();
        studentIDField = new javax.swing.JTextField();
        nameLabel = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        midNameField = new javax.swing.JTextField();
        firstNameField = new javax.swing.JTextField();
        yearOfBirthLabel = new javax.swing.JLabel();
        yearOfBirthField = new javax.swing.JTextField();
        maleRadioButton = new javax.swing.JRadioButton();
        femaleRadioButton = new javax.swing.JRadioButton();
        schoolStageComboBox = new javax.swing.JComboBox<>();
        saveButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("New Student");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        studentIDLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        studentIDLabel.setText("Student ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 24;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 108, 0, 0);
        getContentPane().add(studentIDLabel, gridBagConstraints);

        studentIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.ipadx = 330;
        gridBagConstraints.ipady = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(38, 4, 0, 0);
        getContentPane().add(studentIDField, gridBagConstraints);

        nameLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        nameLabel.setText("Last-Mid-First Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 19;
        gridBagConstraints.ipady = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 16, 0, 0);
        getContentPane().add(nameLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 65;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 13, 0, 0);
        getContentPane().add(lastNameField, gridBagConstraints);

        midNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                midNameFieldActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 17;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 69;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 18, 0, 0);
        getContentPane().add(midNameField, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 65;
        gridBagConstraints.ipady = 16;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(31, 26, 0, 18);
        getContentPane().add(firstNameField, gridBagConstraints);

        yearOfBirthLabel.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        yearOfBirthLabel.setText("Year of Birth");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 17;
        gridBagConstraints.ipady = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 16, 0, 0);
        getContentPane().add(yearOfBirthLabel, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 176;
        gridBagConstraints.ipady = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 12, 0, 0);
        getContentPane().add(yearOfBirthField, gridBagConstraints);

        bg.add(maleRadioButton);
        maleRadioButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        maleRadioButton.setText("Male");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 35, 0, 0);
        getContentPane().add(maleRadioButton, gridBagConstraints);

        bg.add(femaleRadioButton);
        femaleRadioButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        femaleRadioButton.setText("FeMale");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 23;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 16, 0, 0);
        getContentPane().add(femaleRadioButton, gridBagConstraints);

        schoolStageComboBox.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        schoolStageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elementary School", "Middle School", "High School" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 20;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 12, 0, 0);
        getContentPane().add(schoolStageComboBox, gridBagConstraints);

        saveButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 33;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 126, 27, 0);
        getContentPane().add(saveButton, gridBagConstraints);

        clearButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 18, 27, 0);
        getContentPane().add(clearButton, gridBagConstraints);

        cancelButton.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 16;
        gridBagConstraints.ipadx = 24;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 27, 0);
        getContentPane().add(cancelButton, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void midNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_midNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_midNameFieldActionPerformed

    private void studentIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDFieldActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        String studentID = studentIDField.getText();
        String lastName = lastNameField.getText();
        String midName = midNameField.getText();
        String firstName = firstNameField.getText();
        int yearOfBirth = Integer.parseInt(yearOfBirthField.getText());
        String gender = "";
        String schoolStage = "";

        if (maleRadioButton.isSelected()) {
            gender = "Male";
        } else if (femaleRadioButton.isSelected()) {
            gender = "Female";
        } else if (schoolStageComboBox.getSelectedIndex() != -1) {
            schoolStage = (String) schoolStageComboBox.getItemAt(schoolStageComboBox.getSelectedIndex());
        }

        Student stu = new Student(studentID, lastName, midName, firstName, yearOfBirth, gender, schoolStage);
        if (studentManager.addStudent(stu)) {
            JOptionPane.showMessageDialog(this, "Add student ID successful.");
            studentManager.getListStudent().add(stu);
            JOptionPane.showMessageDialog(this, "Adding a new student successful.");
            saveStudents(studentManager.listStudent);
            
        } else {
            JOptionPane.showMessageDialog(this, "Student ID is already exist int the database.");
            
        }
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        studentIDField.setText("");
        lastNameField.setText("");
        midNameField.setText("");
        firstNameField.setText("");
        yearOfBirthField.setText("");
        bg.clearSelection();
        schoolStageComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_clearButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    public void saveStudents(ArrayList<Student>student) {
        try (ObjectOutputStream oos = new ObjectOutputStream(new FileOutputStream("Students.Dat"))) {
            oos.writeObject(student);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error saving  students to file.");
        }
    }

    public void loadStudents(ArrayList<Student>student) {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream("Students.Dat"))) {
            student= (ArrayList<Student>) ois.readObject();
        } catch (IOException | ClassNotFoundException e) {
            JOptionPane.showMessageDialog(this, "Error loading students from file.");
        }
    }

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bg;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JRadioButton femaleRadioButton;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JRadioButton maleRadioButton;
    private javax.swing.JTextField midNameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> schoolStageComboBox;
    private javax.swing.JTextField studentIDField;
    private javax.swing.JLabel studentIDLabel;
    private javax.swing.JTextField yearOfBirthField;
    private javax.swing.JLabel yearOfBirthLabel;
    // End of variables declaration//GEN-END:variables
}
